apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/mikesmitty/nvme_exporter
  # x-release-please-start-version
  newTag: v1.1.2
  # x-release-please-end

resources:
- daemonset.yaml
- service.yaml
- servicemonitor.yaml
